---
# Configuration of the Cycloid stack
version: '4'
name: 'Test Env with ArgoCD'
canonical: 'stack-testenv-argocd'
description: 'Deploy an application test environment using ArgoCD.'
author: 'Cycloid'
image: 'https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/testenv.png'
keywords:
- 'kubernetes'
- 'argocd'
- 'application'
- 'test'
- 'provider:kubernetes'
technologies:
- technology: terraform
  version: 1.8.3

# config:
#   default:
#     pipeline:
#       pipeline:
#         path: pipeline/pipeline.yml
#       variables:
#         path: pipeline/variables.sample.yml
#         destination: '($ .config_root $)/variables.yml'
#     templating:
#       var_path: '($ .config_root $)/vars/templating.json'
#       templates:
#       - paths:
#         - templating/argocd.yml
#         destination: ($ .config_root $)/templating/argocd.yml
#         destination_is_file: true
#       - paths:
#         - templating/testenv.yml
#         destination: ($ .config_root $)/templating/testenv.yml
#         destination_is_file: true
config:
  default:
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: '($ .config_root $)/variables.yml'
    templating:
      var_path: ($ .config_root $)/cy_vars/file.json
      templates:
      - paths:
        - templating/
        destination: ($ .config_root $)/templating/dest_file.yml
        config:
          destination_is_file: true