---
version: "2"
use_cases:
- name: project
  sections:
  - name: GitHub Configuration
    groups:
    - name: Repository Configuration
      technologies: [pipeline]
      vars:
      - name: "Development Stack"
        description: "Select a scaffolding template according to your desired development stack."
        key: git_source_path
        widget: dropdown
        required: true
        type: map
        values:
        - {label: "REST API using Express and Prisma Client", value: "express"}
        - {label: "REST API using Fastify and Prisma Client", value: "fastify"}
        - {label: "REST API using hapi and Prisma Client", value: "hapi"}
        - {label: "REST API using Koa and Prisma Client", value: "koa"}
        - {label: "REST API using NestJS and Prisma Client", value: "nest"}
        - {label: "Web app using Next.js and Prisma Client", value: "nextjs"}
        - {label: "Fullstack app with Nuxt using Vue and Prisma Client", value: "nuxt"}
        - {label: "Web app using React Router 7 and Prisma ORM", value: "react-router-7"}
        - {label: "NodeJS WebApp", value: "simple-counter"}
        - {label: "Java Spring Boot WebApp", value: "java-spring-boot"}
        default: "NodeJS WebApp"
      - name: "Repository Description"
        description: "Description for the GitHub repository"
        key: github_repo_description
        widget: simple_text
        type: string
        default: "Scaffolded software project for ($ .project $)"
        required: false

    - name: kubernetes
      technologies: [pipeline]
      vars:
      - name: "Replicas"
        description: "The number of replicas to deploy in the Kubernetes Cluster."
        key: app_replicas
        widget: slider_range
        type: integer
        default: 3
        values:
          - 1
          - 5
        required: true

    - name: dockerhub
      technologies: [pipeline]
      vars:
      - name: "DockerHub Repository"
        description: "The DockerHub repository to store your application images."
        key: dockerhub_repository
        widget: simple_text
        type: string
        default: "olivier2t/app-test-env"
        required: true

    - name: dns
      technologies: [pipeline]
      vars:
      - name: "DNS Zone"
        description: "The DNS zone to use for the application."
        key: dns_zone
        widget: simple_text
        type: string
        default: "demo.cycloid.io"
        required: true
      # - name: "Repository Visibility"
      #   description: "Visibility level of the GitHub repository"
      #   key: github_repo_visibility
      #   widget: dropdown
      #   type: map
      #   required: true
      #   default: "Private"
      #   values:
      #   - {label: "Private", value: "private"}
      #   - {label: "Public", value: "public"}

    # - name: GitHub Access
    #   technologies: [pipeline]
    #   vars:
    #   - name: "GitHub Personal Access Token"
    #     description: "GitHub Personal Access Token with repo scope to manage repositories and SSH keys."
    #     key: github_pat
    #     widget: cy_cred
    #     widget_config:
    #       display_keys: true
    #       cred_types:
    #         - custom
    #     type: string
    #     default: "((github-pat.token))"
    #     required: true
    #   - name: "GitHub Organization"
    #     description: "This is the organization that will be used to create the repository."
    #     key: github_organization
    #     widget: simple_text
    #     type: string
    #     default: "cycloid-demo"
    #     required: true

    # - name: dockerhub
    #   # technologies: [pipeline, custom]
    #   technologies: [pipeline]
    #   vars:
    #   - name: "DockerHub Repository"
    #     description: "The DockerHub repository to store your application images."
    #     key: dockerhub_repository
    #     widget: simple_text
    #     required: true
    #     type: string
    #     default: "olivier2t/app-test-env"
    #   - name: "DockerHub Username"
    #     description: "The DockerHub username to access the registry."
    #     key: dockerhub_username
    #     widget: cy_cred
    #     widget_config:
    #       display_keys: true
    #       cred_types:
    #         - basic_auth
    #     required: true
    #     type: string
    #     default: "((dockerhub.username))"
    #   - name: "DockerHub Password"
    #     description: "The DockerHub password to access the registry."
    #     key: dockerhub_password
    #     widget: cy_cred
    #     widget_config:
    #       display_keys: true
    #       cred_types:
    #         - basic_auth
    #     required: true
    #     type: string
    #     default: "((dockerhub.password))"

- name: pr-monitor
  sections:
  - name: config
    groups:
    - name: github
      technologies: [pipeline]
      vars:
      - name: "pat"
        description: "GitHub Personal Access Token with repo scope to read the application repository."
        key: github_pat
        widget: cy_cred
        widget_config:
          display_keys: true
          cred_types:
            - custom
        type: string
        default: "((github-pat.token))"
        required: true

      - name: "organization"
        description: "This is the organization that will be used to read the application repository."
        key: github_organization
        widget: simple_text
        type: string
        default: "cycloid-demo"
        required: true

    - name: kubernetes
      technologies: [pipeline]
      vars:
      - name: "Replicas"
        description: "The number of replicas to deploy in the Kubernetes Cluster."
        key: app_replicas
        widget: slider_range
        type: integer
        default: 3
        values:
          - 1
          - 5
        required: true

    - name: dockerhub
      technologies: [pipeline]
      vars:
      - name: "DockerHub Repository"
        description: "The DockerHub repository to store your application images."
        key: dockerhub_repository
        widget: simple_text
        type: string
        default: "olivier2t/app-test-env"
        required: true

    - name: dns
      technologies: [pipeline]
      vars:
      - name: "DNS Zone"
        description: "The DNS zone to use for the application."
        key: dns_zone
        widget: simple_text
        type: string
        default: "demo.cycloid.io"
        required: true

- name: testenv
  sections:
  - name: config
    groups:
    - name: kubernetes
      technologies: [pipeline, custom]
      vars:
      - name: "Replicas"
        description: "The number of replicas to deploy in the Kubernetes Cluster."
        key: app_replicas
        widget: slider_range
        type: integer
        default: 3
        values:
          - 1
          - 5
        required: true

    - name: dockerhub
      technologies: [pipeline, custom]
      vars:
      - name: "DockerHub Repository"
        description: "The DockerHub repository to store your application images."
        key: dockerhub_repository
        widget: simple_text
        type: string
        default: "olivier2t/app-test-env"
        required: true

    - name: dns
      technologies: [pipeline, custom]
      vars:
      - name: "DNS Zone"
        description: "The DNS zone to use for the application."
        key: dns_zone
        widget: simple_text
        type: string
        default: "demo.cycloid.io"
        required: true