resources:
# The repo with our Dockerfile
- name: git_app_code
  type: git
  icon: github-circle
  source:
    uri: ((git_url))
    branch: ((git_branch))
    private_key: ((git_ssh_key))

# Where we will push the image
- name: app_image
  type: registry-image
  icon: docker
  source:
    repository: ((registry_repository))
    username: ((registry_username))
    password: ((registry_password))
    tag: ((git_branch))


groups:
- name: overview
  jobs:
    - build-and-push
    - deploy-app

- name: delete
  jobs:
    - delete-app


jobs:
- name: build-and-push
  plan:
  - get: git_app_code
    trigger: true
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: git_app_code
      outputs:
      - name: image
      params:
        CONTEXT: git_app_code
        DOCKERFILE: git_app_code/Dockerfile-($ .env $)
      caches:
      - path: cache
      run:
        path: build
  - put: app_image
    params:
      image: image/image.tar

- name: deploy-app
  serial: true
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
  - get: app_image
    trigger: true
    passed:
      - build-and-push
  - task: deploy-app
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: olivier2t/toolkit
          tag: latest
      run:
        path: /bin/bash
        args:
        - -ec
        - |
          echo -e "${KUBECONFIG_CONTENT}" >kubeconfig
          export KUBECONFIG="$(pwd)/kubeconfig"
          export K8S_EXTERNAL_IP=$(kubectl config view -o json | jq .clusters[0].cluster.server | gawk -F[/:] '{print $4}')
          export APP_NAME=$(echo ${APP_NAME} | sed 's/_//')
          # if [ "$DATABASE_INTEGRATION" == "true" ]; then
          #   if [ "$DATABASE_ENGINE" == "postgresql" ]; then
          #     if [ "$DATABASE_CLOUD" == "aws" ]; then
          #       export $DATABASE_ENV_VAR_VALUE="postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_AWS}/${DATABASE_NAME}?schema=public"
          #     elif [ "$DATABASE_CLOUD" == "azure" ]; then
          #       export $DATABASE_ENV_VAR_VALUE="postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_AZURE}/${DATABASE_NAME}?schema=public"
          #     fi
          #   elif [ "$DATABASE_ENGINE" == "mysql" ]; then
          #     if [ "$DATABASE_CLOUD" == "aws" ]; then
          #       export $DATABASE_ENV_VAR_VALUE="mysql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_AWS}/${DATABASE_NAME}"
          #     elif [ "$DATABASE_CLOUD" == "azure" ]; then
          #       export $DATABASE_ENV_VAR_VALUE="mysql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_AZURE}/${DATABASE_NAME}"
          #     fi
          #   fi
          # fi
          echo ${APP_ENV_VARS} >app-env-vars.properties
          # echo "${DATABASE_ENV_VAR_NAME}=${DATABASE_ENV_VAR_VALUE}" >>app-env-vars.properties
          # echo "DATABASE_ENGINE=${DATABASE_ENGINE}" >>app-env-vars.properties
          # cat app-env-vars.properties
          kubectl create configmap app-env-vars --from-env-file=app-env-vars.properties
          cat <<-EOF >deploy.yaml
          ---
          apiVersion: v1
          kind: Namespace
          metadata:
            name: ${APP_NAME}
          ---
          # Deployment
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: ${APP_NAME}
            namespace: ${APP_NAME}
          spec:
            replicas: ${APP_REPLICAS}
            selector:
              matchLabels:
                app: ${APP_NAME}
            template:
              metadata:
                labels:
                  app: ${APP_NAME}
              spec:
                terminationGracePeriodSeconds: 0
                containers:
                  - name: ${APP_NAME}
                    image: ${APP_IMAGE_REPO}:${APP_IMAGE_TAG}
                    ports:
                      - containerPort: ${APP_PORT}
                    imagePullPolicy: "Always"
                    envFrom:
                      - configMapRef:
                          name: app-env-vars
          ---
          # Service
          apiVersion: v1
          kind: Service
          metadata:
            name: ${APP_NAME}
            namespace: ${APP_NAME}
          spec:
            selector:
              app: ${APP_NAME}
            ports:
              - port: 80
                targetPort: ${APP_PORT}
          ---
          # Ingress
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: ${APP_NAME}
            namespace: ${APP_NAME}
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          spec:
            ingressClassName: nginx
            rules:
              - host: ${APP_NAME}.${K8S_EXTERNAL_IP}.nip.io
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: ${APP_NAME}
                          port:
                            number: 80
          EOF
          echo "Deploying..."
          kubectl apply -f deploy.yaml
          kubectl rollout restart deployment ${APP_NAME} -n ${APP_NAME}

          export APP_URL=$(kubectl get ing ${APP_NAME} -n ${APP_NAME} | grep ${APP_NAME} | awk '{print $3}')
          export MESSAGE="A test environment have been deployed under <a href='http://${APP_URL}'>http://${APP_URL}</a>"
          echo $MESSAGE
      params:
        KUBECONFIG_CONTENT: ((kubeconfig_content))
        APP_NAME: ($ .project $)-($ .env $)
        APP_PORT: 8080
        APP_REPLICAS: ((app_replicas))
        APP_IMAGE_REPO: ((registry_repository))
        APP_IMAGE_TAG: ($ .env $)
        APP_ENV_VARS: ((app_env_vars))
        # DATABASE_INTEGRATION: ((database_integration))
        # DATABASE_ENV_VAR_NAME: ((database_env_var_name))
        # DATABASE_ENGINE: ((database_engine))
        # DATABASE_CLOUD: ((database_cloud))
        # DATABASE_AWS: ((database_aws))
        # DATABASE_AZURE: ((database_azure))
        # DATABASE_NAME: ((database_name))
        # DATABASE_USERNAME: ((($ .project $)-($ .env $)-database.username))
        # DATABASE_PASSWORD: ((($ .project $)-($ .env $)-database.password))


- name: delete-app
  serial: true
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
  - task: delete-app
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: olivier2t/toolkit
          tag: latest
      run:
        path: /bin/bash
        args:
        - -ec
        - |
          echo -e "${KUBECONFIG_CONTENT}" >kubeconfig
          export KUBECONFIG="$(pwd)/kubeconfig"
          export K8S_EXTERNAL_IP=$(kubectl config view -o json | jq .clusters[0].cluster.server | gawk -F[/:] '{print $4}')
          export APP_NAME=$(echo ${APP_NAME} | sed 's/_//')
          cat <<-EOF >deploy.yaml
          ---
          apiVersion: v1
          kind: Namespace
          metadata:
            name: ${APP_NAME}
          ---
          # Deployment
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: ${APP_NAME}
            namespace: ${APP_NAME}
          spec:
            replicas: ${APP_REPLICAS}
            selector:
              matchLabels:
                app: ${APP_NAME}
            template:
              metadata:
                labels:
                  app: ${APP_NAME}
              spec:
                terminationGracePeriodSeconds: 0
                containers:
                  - name: ${APP_NAME}
                    image: ${APP_IMAGE_REPO}:${APP_IMAGE_TAG}
                    ports:
                      - containerPort: ${APP_PORT}
                    imagePullPolicy: Always
          ---
          # Service
          apiVersion: v1
          kind: Service
          metadata:
            name: ${APP_NAME}
            namespace: ${APP_NAME}
          spec:
            selector:
              app: ${APP_NAME}
            ports:
              - port: 80
                targetPort: ${APP_PORT}
          ---
          # Ingress
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: ${APP_NAME}
            namespace: ${APP_NAME}
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          spec:
            ingressClassName: nginx
            rules:
              - host: ${APP_NAME}.${K8S_EXTERNAL_IP}.nip.io
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: ${APP_NAME}
                          port:
                            number: 80
          EOF
          echo "Deleting..."
          kubectl delete -f deploy.yaml
      params:
        KUBECONFIG_CONTENT: ((kubeconfig_content))
        APP_NAME: ($ .org $)-($ .project $)-($ .env $)
        APP_PORT: 8080
        APP_REPLICAS: 3
        APP_IMAGE_REPO: ((registry_repository))
        APP_IMAGE_TAG: ($ .env $)