---
# Configuration of the Cycloid stack
version: '4'
name: 'Deploy Application Release'
canonical: stack-deploy-idp
author: Cycloid
description: |
  Deploy an application release to a Kubernetes cluster using ArgoCD manifests.
image: |
  https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/argocd.svg
keywords:
  - 'kubernetes'
  - 'argocd'
  - 'application'
  - 'release'
technologies:
- technology: terraform
  version: 1.8.3

config:
  argocd:
    name: 'ArgoCD'
    description: 'Deploy the application release to a Kubernetes cluster using ArgoCD manifests.'
    cloud_provider: kubernetes
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: '($ .config_root $)/pipeline/variables.yml'
  aws:
    name: 'AWS'
    description: 'Deploy the application release to an EC2 instance using Terraform and Ansible.'
    cloud_provider: aws
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: '($ .config_root $)/pipeline/variables.yml'
    terraform:
      main:
        path: 'terraform/aws/main.tf'
        destination: '($ .config_root $)/terraform/aws/main.tf'
  azure:
    name: 'Azure'
    description: 'Deploy the application release to an Azure virtual machine using Terraform and Ansible.'
    cloud_provider: azure
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: '($ .config_root $)/pipeline/variables.yml'
    terraform:
      main:
        path: 'terraform/azure/main.tf'
        destination: '($ .config_root $)/terraform/azure/main.tf'