---
version: "2"
use_cases:
- name: cycloid-common
  sections:
  - name: config
    groups:
    - name: "Application Image"
      technologies: [pipeline]
      vars:
      - name: "Application Image Tag"
        description: "The application release tag to use for the container image."
        key: app_image_tag
        widget: simple_text
        required: true
        type: string
        default: "1.0.0"
- name: argocd
  - name: config
    groups:
    - name: "Kubernetes Configuration"
      technologies: [pipeline]
      vars:
      - name: "Replicas"
        description: "The number of replicas to deploy in the Kubernetes Cluster."
        key: app_replicas
        widget: slider_range
        type: integer
        default: 3
        values:
          - 1
          - 5
        required: true
- name: aws
    sections:
    - name: config
      groups:
      - name: "AWS Configuration"
        technologies: [pipeline]
        vars:
        - name: "AWS Region"
          description: "The AWS region to deploy the application to."
          key: aws_region
          widget: simple_text
          type: string
          default: "us-east-1"
          required: true
        - name: "AWS Instance Type"
          description: "The AWS instance type to deploy the application to."
          key: aws_instance_type
          widget: simple_text
          type: string
          default: "t3.medium"
          required: true

