---
version: "2"
use_cases:
- name: default
  sections:
  - name: config
    groups:
    - name: "Application Image"
      # technologies: [pipeline, templating]
      technologies: [pipeline]
      vars:
      - name: "Application Image Tag"
        description: "The application release tag to use for the container image."
        key: app_image_tag
        widget: simple_text
        required: true
        type: string
        default: "1.0.0"
      # - name: "DockerHub Repository"
      #   description: "The DockerHub repository to store your application images."
      #   key: dockerhub_repository
      #   widget: simple_text
      #   required: true
      #   type: string
      #   default: "olivier2t/app-test-env"
      # - name: "DockerHub Username"
      #   description: "The DockerHub username to access the registry."
      #   key: dockerhub_username
      #   widget: cy_cred
      #   widget_config:
      #     display_keys: true
      #     cred_types:
      #       - basic_auth
      #   required: true
      #   type: string
      #   default: "((dockerhub.username))"
      # - name: "DockerHub Password"
      #   description: "The DockerHub password to access the registry."
      #   key: dockerhub_password
      #   widget: cy_cred
      #   widget_config:
      #     display_keys: true
      #     cred_types:
      #       - basic_auth
      #   required: true
      #   type: string
      #   default: "((dockerhub.password))"
    - name: "Kubernetes Configuration"
      technologies: [pipeline]
      vars:
      - name: "Replicas"
        description: "The number of replicas to deploy in the Kubernetes Cluster."
        key: app_replicas
        widget: slider_range
        type: integer
        default: 3
        values:
          - 1
          - 5
        required: true