---
# Configuration of the Cycloid stack
version: '4'
name: 'GitOps Software Project (GitHub)'
canonical: stack-project-github-gitops-idp
author: Cycloid
description: |
  Create a GitHub repository and scaffold a new project with my organization best practices and security rules. Deploy a Kind cluster with ArgoCD to manage the project test environments in a GitOps way.
image: |
  https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/git.png
keywords:
  - 'git'
  - 'IDP'
  - 'Internal Developer Platform'
  - 'developer'
  - 'application'
  - 'GitHub'
  - 'ArgoCD'
  - 'Kind'
  - 'Kubernetes'
technologies:
- technology: terraform
  version: 1.8.3

config:
  project:
    name: 'Project Initialization'
    description: 'Initialize a new Software Project by scaffolding a new GitHub repository with organization best practices.'
    pipeline:
      pipeline:
        path: pipeline/project/pipeline.yml
      variables:
        path: pipeline/project/variables.sample.yml
        destination: '($ .config_root $)/pipeline/project/variables.yml'
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ .config_root $)/terraform/main.tf'

  pr:
    name: 'Pull Request'
    description: 'Automatically create a testenv for each new pull request.'
    pipeline:
      pipeline:
        path: pipeline/pr/pipeline.yml
      variables:
        path: pipeline/pr/variables.sample.yml
        destination: '($ .config_root $)/pipeline/pr/variables.yml'

  testenv:
    name: 'Test Environment'
    description: 'Deploy an Application Test Environment using ArgoCD manifests.'
    pipeline:
      pipeline:
        path: pipeline/testenv/pipeline.yml
      variables:
        path: pipeline/testenv/variables.sample.yml
        destination: '($ .config_root $)/pipeline/testenv/variables.yml'
    # templating:
    #   var_path: ($ .config_root $)/vars/templating.json
    #   templates:
    #   - paths:
    #     - templating/
    #     destination: ($ .config_root $)/templating/