---
# Configuration of the Cycloid stack
version: '4'
name: 'Test Env with ArgoCD'
canonical: 'stack-testenv-argocd-idp'
description: 'Deploy an application test environment using ArgoCD.'
author: 'Cycloid'
image: 'https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/testenv.png'
keywords:
- 'kubernetes'
- 'argocd'
- 'application'
- 'test'
- 'provider:kubernetes'
technologies:
- technology: terraform
  version: 1.8.3

config:
  default:
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: '($ .config_root $)/variables.yml'
    templating:
      var_path: '($ .config_root $)/vars/templating.json'
      templates:
      - paths:
        - templating/
        destination: ($ .config_root $)/templating/