resources:
# The repo with our Dockerfile
- name: git_app_code
  type: git
  icon: github-circle
  source:
    uri: ((app_git_url))
    branch: ((app_git_branch))
    private_key: ((app_git_ssh_key))

# Where we will push the image
- name: app_image
  type: registry-image
  icon: docker
  source:
    repository: ((dockerhub_repository))
    username: ((((dockerhub_cred)).username))
    password: ((((dockerhub_cred)).password))
    tag: ((app_git_branch))

# The repo with our manifests
- name: git_manifests
  type: git
  icon: github-circle
  source:
    uri: ((manifests_git_url))
    branch: ((manifests_git_branch))
    private_key: ((manifests_git_ssh_key))

# The config git where the geenrated manifests are stored
- name: git_config_templates
  type: git
  icon: github-circle
  source:
    uri: ($ .cr_url $)
    branch: ($ .cr_branch $)
    ($- if eq .cr_cred_type "basic_auth" $)
    username: ((($ .cr_cred_path $).username))
    password: ((($ .cr_cred_path $).password))
    ($- end $)
    ($- if eq .cr_cred_type "ssh" $)
    private_key: ((($ .cr_cred_path $).ssh_key))
    ($- end $)
    paths:
      - ($ .config_root $)/templating/*

groups:
- name: overview
  jobs:
    - build-and-push
    - generate-manifests

- name: delete
  jobs:
    - delete-app


jobs:
- name: build-and-push
  serial: true
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
  - get: git_app_code
    trigger: true
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: git_app_code
      outputs:
      - name: image
      params:
        CONTEXT: git_app_code
        DOCKERFILE: git_app_code/Dockerfile
      caches:
      - path: cache
      run:
        path: build
  - put: app_image
    params:
      image: image/image.tar

- name: generate-manifests
  serial: true
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
  - get: app_image
    trigger: true
    passed:
      - build-and-push
  - get: git_config_templates
    trigger: true
    passed:
      - build-and-push
  - get: git_manifests
  - task: manifests
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: olivier2t/toolkit
          tag: latest
      inputs:
      - name: git_manifests
      - name: git_config_templates
      - name: app_image
      outputs:
      - name: git_manifests
      run:
        path: /bin/bash
        args:
        - -ec
        - |
          echo "Generating manifests..."
          mkdir -p git_manifests/($ .project $)-($ .env $)-($ .component $)
          export K8S_EXTERNAL_IP = $(echo ${KUBECONFIG_CONTENT} | grep "server: https" | head -1 | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])')
          for file in git_config_templates/*; do
            envsubst < $file > git_manifests/($ .project $)-($ .env $)-($ .component $)/$(basename $file)
          done
          cd git_manifests
          git add .
          git commit -m "Add ($ .project $)-($ .env $)-($ .component $) manifests"
      params:
        KUBECONFIG_CONTENT: ((kubeconfig_content))
  - put: git_manifests
    params:
      repository: git_manifests


- name: delete-app
  serial: true
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
  - get: git_manifests
  - task: delete-app
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: olivier2t/toolkit
          tag: latest
      run:
        path: /bin/bash
        args:
        - -ec
        - |
          echo "Deleting..."
          rm -rf git_manifests/($ .project $)-($ .env $)-($ .component $)
          cd git_manifests
          git add .
          git commit -m "Delete ($ .project $)-($ .env $)-($ .component $) manifests"
  - put: git_manifests
    params:
      repository: git_manifests
