resources:
# Where we will get the image from the registry
- name: app_image
  type: registry-image
  icon: docker
  source:
    repository: ((dockerhub_repository))
    username: ((dockerhub_username))
    password: ((dockerhub_password))
    tag: "($ .org $)-($ .project $)-((app_image_tag))"

# The repo with our manifests
- name: git_manifests
  type: git
  icon: github-circle
  source:
    uri: ((manifests_git_url))
    branch: ((manifests_git_branch))
    private_key: ((manifests_git_ssh_key))

# The config git where the generated manifests are stored
# - name: git_config_templates
#   type: git
#   icon: github-circle
#   source:
#     uri: ($ .cr_url $)
#     branch: ($ .cr_branch $)
#     ($- if eq .cr_cred_type "basic_auth" $)
#     username: ((($ .cr_cred_path $).username))
#     password: ((($ .cr_cred_path $).password))
#     ($- end $)
#     ($- if eq .cr_cred_type "ssh" $)
#     private_key: ((($ .cr_cred_path $).ssh_key))
#     ($- end $)
#     paths:
#       - ($ .config_root $)/*
- name: git_stacks
  type: git
  icon: github-circle
  source:
    uri: ($ .scs_url $)
    branch: ($ .scs_branch $)
    ($- if eq .scs_cred_type "basic_auth" $)
    username: ((($ .scs_cred_path $).username))
    password: ((($ .scs_cred_path $).password))
    ($- end $)
    ($- if eq .scs_cred_type "ssh" $)
    private_key: ((($ .scs_cred_path $).ssh_key))
    ($- end $)
    paths:
      - ($ .stack_path $)/templating/*

groups:
- name: overview
  jobs:
    - generate-manifests

- name: delete
  jobs:
    - delete-app


jobs:
- name: generate-manifests
  serial: true
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
  - in_parallel:
    - get: app_image
      trigger: true
    - get: git_stacks
      trigger: true
    - get: git_manifests
  - task: manifests
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: olivier2t/toolkit
          tag: latest
      inputs:
      - name: git_manifests
      - name: git_stacks
      - name: app_image
      outputs:
      - name: git_manifests
      run:
        path: /bin/bash
        args:
        - -c
        - |
          set +e
          echo "Generating manifests..."
          mkdir -p git_manifests/($ .project $)-($ .env $)
          export K8S_EXTERNAL_IP=$(echo ${KUBECONFIG_CONTENT} | grep "server: https" | head -1 | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])')
          ls -la git_stacks/($ .stack_path $)/templating/*
          for file in git_stacks/($ .stack_path $)/templating/*; do
            echo "Processing $file"
            envsubst < $file > git_manifests/($ .project $)-($ .env $)/$(basename $file)
          done
          cd git_manifests
          git config --global user.email "noreply@cycloid.io"
          git config --global user.name "Cycloid Platform"
          git add .
          git diff-index --quiet HEAD || git commit -m "Add ($ .project $)-($ .env $)-($ .component $) manifests"
          echo "✅ Environment deployed at http://${ORG}-${PROJECT}-${ENV}.${K8S_EXTERNAL_IP}.nip.io and ArgoCD at http://argocd.${K8S_EXTERNAL_IP}.nip.io"
      params:
        KUBECONFIG_CONTENT: ((kubeconfig_content))
        ORG: ($ .org $)
        PROJECT: ($ .project $)
        ENV: ($ .env $)
        COMPONENT: ($ .component $)
        DH_REPO: ((dockerhub_repository))
        DH_IMAGE_TAG: "($ .org $)-($ .project $)-((app_image_tag))"
        APP_REPLICAS: ((app_replicas))
  - put: git_manifests
    params:
      repository: git_manifests
  - task: restart-app
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: olivier2t/toolkit
          tag: latest
      inputs:
      - name: git_manifests
      - name: git_stacks
      - name: app_image
      outputs:
      - name: git_manifests
      run:
        path: /bin/bash
        args:
        - -c
        - |
          set +e
          echo "Restarting application..."
          export K8S_EXTERNAL_IP=$(echo ${KUBECONFIG_CONTENT} | grep "server: https" | head -1 | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])')
          until argocd login argocd.${K8S_EXTERNAL_IP}.nip.io --username admin --password ${ARGOCD_ADMIN_PASSWORD} --grpc-web --insecure; do sleep 5; done
          argocd app sync app-of-apps --force
          # echo "$KUBECONFIG_CONTENT" > kubeconfig.yaml
          # kubectl --kubeconfig kubeconfig.yaml rollout restart deployment ${ORG}-${PROJECT}-${ENV}-${COMPONENT} -n ${ORG}-${PROJECT}-${ENV}-${COMPONENT}
      params:
        KUBECONFIG_CONTENT: ((kubeconfig_content))
        ARGOCD_ADMIN_PASSWORD: ((infrastructure-($ .env $)-argocd-admin-password.password))
        ORG: ($ .org $)
        PROJECT: ($ .project $)
        ENV: ($ .env $)
        COMPONENT: ($ .component $)


- name: delete-app
  serial: true
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
  - get: git_manifests
  - task: delete-app
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: olivier2t/toolkit
          tag: latest
      inputs:
      - name: git_manifests
      run:
        path: /bin/bash
        args:
        - -ec
        - |
          echo "Deleting..."
          cd git_manifests
          rm -rf ($ .project $)-($ .env $)/
          git config --global user.email "noreply@cycloid.io"
          git config --global user.name "Cycloid Platform"
          git add .
          git diff-index --quiet HEAD || git commit -m "Delete ($ .project $)-($ .env $) manifests"
  - put: git_manifests
    params:
      repository: git_manifests
