apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ($ .org $)-($ .component $)
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=($ .dockerhub_repository $):($ .org $)-($ .project $)-($ .app_image_tag $)
    argocd-image-updater.argoproj.io/app.update-strategy: digest
    argocd-image-updater.argoproj.io/app.pull-secret: secret:argocd/dockerhub-creds
spec:
  project: default
  source:
    repoURL: ($ .org $)-manifests
    targetRevision: main
    path: ($ .component $)
  destination:
    server: https://kubernetes.default.svc
    namespace: ($ .org $)-($ .component $)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true