---
apiVersion: v1
kind: Namespace
metadata:
  name: ${DH_IMAGE_TAG}
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DH_IMAGE_TAG}
  namespace: ${DH_IMAGE_TAG}
spec:
  replicas: ${APP_REPLICAS}
  selector:
    matchLabels:
      app: ${DH_IMAGE_TAG}
  template:
    metadata:
      labels:
        app: ${DH_IMAGE_TAG}
    spec:
      containers:
        - name: ${DH_IMAGE_TAG}
          image: ${DH_REPO}:${DH_IMAGE_TAG}
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: ${DH_IMAGE_TAG}
  namespace: ${DH_IMAGE_TAG}
spec:
  selector:
    app: ${DH_IMAGE_TAG}
  ports:
    - port: 80
      targetPort: 8080
---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${DH_IMAGE_TAG}
  namespace: ${DH_IMAGE_TAG}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: ${DH_IMAGE_TAG}.${K8S_EXTERNAL_IP}.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${DH_IMAGE_TAG}
                port:
                  number: 80
  tls:
    - hosts:
        - ${DH_IMAGE_TAG}.${K8S_EXTERNAL_IP}.nip.io
      secretName: ${DH_IMAGE_TAG}-tls
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: ${DH_IMAGE_TAG}
#   namespace: ${DH_IMAGE_TAG}
# spec:
#   secretName: ${DH_IMAGE_TAG}-tls
#   issuerRef:
#     name: ssl-issuer
#     kind: ClusterIssuer
#   dnsNames:
#     - ${DH_IMAGE_TAG}.${K8S_EXTERNAL_IP}.nip.io