apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ($ .project $)-($ .env $)-($ .component $)
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ($ .argocd_git_url $)
    targetRevision: ($ .argocd_git_branch $)
    path: ($ .project $)-($ .env $)-($ .component $)
  destination:
    server: https://kubernetes.default.svc
    namespace: ($ .project $)-($ .env $)-($ .component $)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true