---
version: "2"
use_cases:
- name: default
  sections:
  - name: Kubernetes Single Node K3s
    groups:
    - name: ArgoCD
      technologies: [terraform]
      vars:
      - name: "ArgoCD Version"
        description: "Version of ArgoCD to deploy"
        key: argocd_version
        widget: simple_text
        type: string
        default: "v3.1.8"
        required: true
        validations: 
        - regexp: "^v\\d+\\.\\d+\\.\\d+$" 
          error_message: "Please enter a valid ArgoCD version such as v3.1.8"

    - name: Day-2 Operations
      technologies: [pipeline]
      vars:
      - name: "Instance status"
        description: "Status for the deployed instances."
        key: vm_instance_status
        widget: radios
        type: string
        default: "Started"
        values:
            - "Started"
            - "Stopped"
        required: true
      - name: "Destroy Timer"
        description: "The number of minutes to wait before automatically destroying the infrastructure after creation."
        key: destroy_timer_in_minutes
        widget: number
        type: integer
        default: 60
        required: true

    - name: Infrastructure Configuration
      technologies: [terraform]
      vars:
      - name: "Instance type"
        description: "Instance type for the VM."
        key: vm_instance_type
        widget: dropdown
        type: string
        default: "t3a.medium"
        values_ref: https://cycloid-demo-stackforms-values.s3.eu-west-1.amazonaws.com/aws-ec2-instance-types.json
        required: true
      - name: "Disk size"
        unit: Go
        description: "Disk size for the VM."
        key: vm_disk_size
        widget: slider_range
        type: integer
        default: 20
        values:
            - 20
            - 250
        required: true

    - name: Advanced Configuration
      technologies: [pipeline]
      vars:
      - name: "Enable advanced infrastructure configuration"
        description: "Enable advanced infrastructure configuration to configure the infrastructure with custom credentials and settings."
        key: enable_advanced_config
        widget: switch
        required: true
        type: boolean
        default: false

    - name: Access Configuration
      technologies: [pipeline]
      condition: '$enable_advanced_config == true'
      vars:
      - name: "AWS Account"
        description: "The AWS account where to deploy the infrastructure. It contains access key and secret key."
        key: aws_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - aws
        type: string
        default: "((aws))"
        required: true

      - name: "AWS Region"
        description: "AWS region to use for Terraform."
        key: aws_region
        widget: auto_complete
        type: string
        default: "eu-west-1"
        values_ref: https://cycloid-demo-stackforms-values.s3.eu-west-1.amazonaws.com/aws-regions.json
        required: true