---
version: "2"
use_cases:
- name: default
  sections:
  - name: Software Project Onboarding
    groups:
    - name: Cycloid New Organization
      technologies: [pipeline]
      vars:
      - name: "Cycloid organization canonical name to create"
        description: "Child Cycloid organization canonical name to create."
        key: cy_child_org_canonical
        widget: simple_text
        type: string
        default: "($ .component $)"
        validations: 
        - regexp: "^[a-z0-9-]+$"
          error_message: "Please enter a valid Cycloid organization canonical name. It can only contain lowercase letters, numbers and hyphens."
        required: true
    - name: Enable Advanced Configuration
      technologies: [pipeline]
      vars:
      - name: "Enable advanced configuration"
        description: "Enable advanced configuration to configure the child organization with custom credentials and settings."
        key: enable_advanced_config
        widget: switch
        type: boolean
        default: false
        required: false
    - name: Advanced Configuration
      technologies: [pipeline]
      condition: '$enable_advanced_config == true'
      vars:
      - name: "Cycloid API key"
        description: "Cycloid organization API key allowing to create and manage child organizations."
        key: cy_api_key
        widget: cy_cred
        widget_config:
          display_keys: true
          cred_types:
            - custom
        type: string
        default: "((admin-api-key.key))"
        required: true
      - name: "GitHub PAT"
        description: "GitHub Personal Access Token allowing to scaffold application git repositoryand create ArgoCD git repository."
        key: github_pat
        widget: cy_cred
        widget_config:
          display_keys: true
          cred_types: ["custom"]
        type: string
        default: "((github-pat.token))"
        required: true
      - name: "GitHub SSH key to provision in the child organization"
        description: "GitHub SSH key in OpenSSH format to provision to access the Cycloid GitHub repositories in the child organization."
        key: github_private_key_openssh
        widget: cy_cred
        widget_config:
          display_keys: true
          cred_types: ["ssh"]
        type: string
        default: "((git-ssh-child-org.ssh_key))"
        required: true
      - name: "AWS account for Terraform backend"
        description: "The AWS account where to create the S3 bucket and IAM user to access the Cycloid child organization Terraform backend."
        key: aws_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - aws
        type: string
        default: "((aws))"
        required: true
      - name: "AWS region for Terraform backend"
        description: "The AWS region where to create the S3 bucket used as the Cycloid child organization Terraform backend."
        key: aws_region
        widget: auto_complete
        type: string
        values_ref: https://cycloid-demo-stackforms-values.s3.eu-west-1.amazonaws.com/aws-regions.json
        default: eu-west-1
        validations: 
        - regexp: "^[a-z]{2}-[a-z]+-\\d+$" 
          error_message: "Please enter a valid AWS region such as us-east-3"
        required: true
      - name: "AWS Account for the new software project"
        description: "AWS account to use for the new software project."
        key: aws_cred_infra
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - aws
        type: string
        default: "((aws))"
        required: true

    - name: Team Members
      technologies: [pipeline]
      vars:
      - name: "CCP/CSP Team members"
        description: "CCP/CSP team members to invite to the new software project."
        key: team_members_infrastructure
        widget: dropdown
        type: array
        default: []
        required: true
        values:
        - {label: "Olivier Infrastructure", value: "olivier+infra@cycloid.io"}
        - {label: "Olivier Developer", value: "olivier+dev@cycloid.io"}
        - {label: "Olivier Integrator", value: "olivier+integrator@cycloid.io"}
        - {label: "Gaël Lambert", value: "gael.lambert@cycloid.io"}
        - {label: "Frédéric Barras Hampel", value: "frederic.hampel@cycloid.io"}
        - {label: "Florian Lambert", value: "florian.lambert@cycloid.io"}
        - {label: "Vincent Mazières", value: "vincent.mazieres@cycloid.io"}
        - {label: "Sébastien Roux", value: "sebastien.roux@cycloid.io"}
        - {label: "Guillaume Lambert", value: "guillaume.lambert@cycloid.io"}
        - {label: "Laurent Malraux", value: "laurent.malraux@cycloid.io"}
        - {label: "Thomas Billot", value: "thomas.billot@cycloid.io"}
        - {label: "Gauthier Gaudet", value: "gauthier.gaudet@cycloid.io"}
        - {label: "Aurélien Le Louarn", value: "aurelien.lelouarn@cycloid.io"}
        - {label: "Cyril Bousquet", value: "cyril.bousquet@cycloid.io"}
        - {label: "Guillaume Dupont", value: "guillaume.dupont@cycloid.io"}
        - {label: "Mathieu Chambon", value: "mathieu.chambon@cycloid.io"}
        - {label: "Mickaël Faure", value: "mickael.faure@cycloid.io"}
        - {label: "Nicolas Lacroix", value: "nicolas.lacroix@cycloid.io"}
        - {label: "Maxime Valette", value: "maxime.valette@cycloid.io"}
        - {label: "Mathieu Duval", value: "mathieu.duval@cycloid.io"}
        - {label: "Antoine Martin", value: "antoine.martin@cycloid.io"}
        - {label: "Baptiste Caille", value: "baptiste.caille@cycloid.io"}
        - {label: "Quentin Charpentier", value: "quentin.charpentier@cycloid.io"}
        - {label: "Rémi Robillard", value: "remi.robillard@cycloid.io"}
        - {label: "Simon Léon", value: "simon.leon@cycloid.io"}
        - {label: "Guillaume Seguin", value: "guillaume.seguin@cycloid.io"}
        - {label: "Thibault Boucard", value: "thibault.boucard@cycloid.io"}
        - {label: "Vincent Hautier", value: "vincent.hautier@cycloid.io"}
        - {label: "Florian Lauby", value: "florian.lauby@cycloid.io"}
        - {label: "Nicolas Le Bras", value: "nicolas.lebras@cycloid.io"}
        - {label: "Jérémy Leblanc", value: "jeremy.leblanc@cycloid.io"}
        - {label: "Cédric Serafin", value: "cedric.serafin@cycloid.io"}
        - {label: "Guillaume Leclerc", value: "guillaume.leclerc@cycloid.io"}
        - {label: "Nicolas Morel", value: "nicolas.morel@cycloid.io"}
        - {label: "Romain Bouffard", value: "romain.bouffard@cycloid.io"}
        - {label: "Thomas Guigou", value: "thomas.guigou@cycloid.io"}
        - {label: "Théo Lelievre", value: "theo.lelievre@cycloid.io"}
        - {label: "Hugo Maccario", value: "hugo.maccario@cycloid.io"}
        widget_config:
          multiselect: true

      - name: "SODS Team members"
        description: "SODS team members to invite to the new software project."
        key: team_members_application
        widget: dropdown
        type: array
        default: []
        required: true
        values:
        - {label: "Olivier Infrastructure", value: "olivier+infra@cycloid.io"}
        - {label: "Olivier Developer", value: "olivier+dev@cycloid.io"}
        - {label: "Olivier Integrator", value: "olivier+integrator@cycloid.io"}
        - {label: "Gaël Lambert", value: "gael.lambert@cycloid.io"}
        - {label: "Frédéric Barras Hampel", value: "frederic.hampel@cycloid.io"}
        - {label: "Florian Lambert", value: "florian.lambert@cycloid.io"}
        - {label: "Vincent Mazières", value: "vincent.mazieres@cycloid.io"}
        - {label: "Sébastien Roux", value: "sebastien.roux@cycloid.io"}
        - {label: "Guillaume Lambert", value: "guillaume.lambert@cycloid.io"}
        - {label: "Laurent Malraux", value: "laurent.malraux@cycloid.io"}
        - {label: "Thomas Billot", value: "thomas.billot@cycloid.io"}
        - {label: "Gauthier Gaudet", value: "gauthier.gaudet@cycloid.io"}
        - {label: "Aurélien Le Louarn", value: "aurelien.lelouarn@cycloid.io"}
        - {label: "Cyril Bousquet", value: "cyril.bousquet@cycloid.io"}
        - {label: "Guillaume Dupont", value: "guillaume.dupont@cycloid.io"}
        - {label: "Mathieu Chambon", value: "mathieu.chambon@cycloid.io"}
        - {label: "Mickaël Faure", value: "mickael.faure@cycloid.io"}
        - {label: "Nicolas Lacroix", value: "nicolas.lacroix@cycloid.io"}
        - {label: "Maxime Valette", value: "maxime.valette@cycloid.io"}
        - {label: "Mathieu Duval", value: "mathieu.duval@cycloid.io"}
        - {label: "Antoine Martin", value: "antoine.martin@cycloid.io"}
        - {label: "Baptiste Caille", value: "baptiste.caille@cycloid.io"}
        - {label: "Quentin Charpentier", value: "quentin.charpentier@cycloid.io"}
        - {label: "Rémi Robillard", value: "remi.robillard@cycloid.io"}
        - {label: "Simon Léon", value: "simon.leon@cycloid.io"}
        - {label: "Guillaume Seguin", value: "guillaume.seguin@cycloid.io"}
        - {label: "Thibault Boucard", value: "thibault.boucard@cycloid.io"}
        - {label: "Vincent Hautier", value: "vincent.hautier@cycloid.io"}
        - {label: "Florian Lauby", value: "florian.lauby@cycloid.io"}
        - {label: "Nicolas Le Bras", value: "nicolas.lebras@cycloid.io"}
        - {label: "Jérémy Leblanc", value: "jeremy.leblanc@cycloid.io"}
        - {label: "Cédric Serafin", value: "cedric.serafin@cycloid.io"}
        - {label: "Guillaume Leclerc", value: "guillaume.leclerc@cycloid.io"}
        - {label: "Nicolas Morel", value: "nicolas.morel@cycloid.io"}
        - {label: "Romain Bouffard", value: "romain.bouffard@cycloid.io"}
        - {label: "Thomas Guigou", value: "thomas.guigou@cycloid.io"}
        - {label: "Théo Lelievre", value: "theo.lelievre@cycloid.io"}
        - {label: "Hugo Maccario", value: "hugo.maccario@cycloid.io"}
        widget_config:
          multiselect: true

      - name: "CSDS Team members"
        description: "CSDS team members to invite to the new software project."
        key: team_members_integration
        widget: dropdown
        type: array
        default: []
        required: true
        values:
        - {label: "Olivier Infrastructure", value: "olivier+infra@cycloid.io"}
        - {label: "Olivier Developer", value: "olivier+dev@cycloid.io"}
        - {label: "Olivier Integrator", value: "olivier+integrator@cycloid.io"}
        - {label: "Gaël Lambert", value: "gael.lambert@cycloid.io"}
        - {label: "Frédéric Barras Hampel", value: "frederic.hampel@cycloid.io"}
        - {label: "Florian Lambert", value: "florian.lambert@cycloid.io"}
        - {label: "Vincent Mazières", value: "vincent.mazieres@cycloid.io"}
        - {label: "Sébastien Roux", value: "sebastien.roux@cycloid.io"}
        - {label: "Guillaume Lambert", value: "guillaume.lambert@cycloid.io"}
        - {label: "Laurent Malraux", value: "laurent.malraux@cycloid.io"}
        - {label: "Thomas Billot", value: "thomas.billot@cycloid.io"}
        - {label: "Gauthier Gaudet", value: "gauthier.gaudet@cycloid.io"}
        - {label: "Aurélien Le Louarn", value: "aurelien.lelouarn@cycloid.io"}
        - {label: "Cyril Bousquet", value: "cyril.bousquet@cycloid.io"}
        - {label: "Guillaume Dupont", value: "guillaume.dupont@cycloid.io"}
        - {label: "Mathieu Chambon", value: "mathieu.chambon@cycloid.io"}
        - {label: "Mickaël Faure", value: "mickael.faure@cycloid.io"}
        - {label: "Nicolas Lacroix", value: "nicolas.lacroix@cycloid.io"}
        - {label: "Maxime Valette", value: "maxime.valette@cycloid.io"}
        - {label: "Mathieu Duval", value: "mathieu.duval@cycloid.io"}
        - {label: "Antoine Martin", value: "antoine.martin@cycloid.io"}
        - {label: "Baptiste Caille", value: "baptiste.caille@cycloid.io"}
        - {label: "Quentin Charpentier", value: "quentin.charpentier@cycloid.io"}
        - {label: "Rémi Robillard", value: "remi.robillard@cycloid.io"}
        - {label: "Simon Léon", value: "simon.leon@cycloid.io"}
        - {label: "Guillaume Seguin", value: "guillaume.seguin@cycloid.io"}
        - {label: "Thibault Boucard", value: "thibault.boucard@cycloid.io"}
        - {label: "Vincent Hautier", value: "vincent.hautier@cycloid.io"}
        - {label: "Florian Lauby", value: "florian.lauby@cycloid.io"}
        - {label: "Nicolas Le Bras", value: "nicolas.lebras@cycloid.io"}
        - {label: "Jérémy Leblanc", value: "jeremy.leblanc@cycloid.io"}
        - {label: "Cédric Serafin", value: "cedric.serafin@cycloid.io"}
        - {label: "Guillaume Leclerc", value: "guillaume.leclerc@cycloid.io"}
        - {label: "Nicolas Morel", value: "nicolas.morel@cycloid.io"}
        - {label: "Romain Bouffard", value: "romain.bouffard@cycloid.io"}
        - {label: "Thomas Guigou", value: "thomas.guigou@cycloid.io"}
        - {label: "Théo Lelievre", value: "theo.lelievre@cycloid.io"}
        - {label: "Hugo Maccario", value: "hugo.maccario@cycloid.io"}
        widget_config:
          multiselect: true

