resources:
# The repo with our Dockerfile (if we build the container image)
# - name: git_app_code
#   type: git
#   icon: github-circle
#   source:
#     uri: ((app_git_url))
#     branch: ((app_git_branch))
#     private_key: ((app_git_ssh_key))

# Where we will get the image
- name: app_image
  type: registry-image
  icon: docker
  source:
    repository: ((registry_repository))
    username: ((registry_username))
    password: ((registry_password))
    tag: "($ .org $)-($ .project $)-((app_image_tag))"

# The repo with our manifests
- name: git_manifests
  type: git
  icon: github-circle
  source:
    uri: ((manifests_git_url))
    branch: ((manifests_git_branch))
    private_key: ((manifests_git_ssh_key))

# The config git where the generated manifests are stored
- name: git_config
  type: git
  icon: github-circle
  source:
    uri: ($ .cr_url $)
    branch: ($ .cr_branch $)
    ($- if eq .cr_cred_type "basic_auth" $)
    username: ((($ .cr_cred_path $).username))
    password: ((($ .cr_cred_path $).password))
    ($- end $)
    ($- if eq .cr_cred_type "ssh" $)
    private_key: ((($ .cr_cred_path $).ssh_key))
    ($- end $)
    paths:
      - ($ .config_root $)/templating/*

groups:
- name: overview
  jobs:
    # - build-and-push
    - push-manifests

- name: delete
  jobs:
    - delete-app


jobs:
# - name: build-and-push
#   serial: true
#   max_in_flight: 1
#   build_logs_to_retain: 10
#   plan:
#   - get: git_app_code
#     trigger: true
#   - task: build-task-image
#     privileged: true
#     config:
#       platform: linux
#       image_resource:
#         type: registry-image
#         source:
#           repository: concourse/oci-build-task
#       inputs:
#       - name: git_app_code
#       outputs:
#       - name: image
#       params:
#         CONTEXT: git_app_code
#         DOCKERFILE: git_app_code/Dockerfile
#       caches:
#       - path: cache
#       run:
#         path: build
#   - put: app_image
#     params:
#       image: image/image.tar

- name: push-manifests
  serial: true
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
  - in_parallel:
    - get: app_image
      trigger: true
    - get: git_config
      trigger: true
    - get: git_manifests
  - task: manifests
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: olivier2t/toolkit
          tag: latest
      inputs:
      - name: git_manifests
      - name: git_config
      - name: app_image
      outputs:
      - name: git_manifests
      run:
        path: /bin/bash
        args:
        - -c
        - |
          set +e
          echo "Pushing manifests..."
          mkdir -p git_manifests/${APP_IMAGE_TAG}
          # Uses as is the Cycloid generated manifests
          cp -r git_config/($ .config_root $)/templating/* git_manifests/${APP_IMAGE_TAG}/
          # Uncomment the following if you have custom variables to replace in the manifests
          # for file in git_config/($ .config_root $)/templating/*; do
          #   echo "Processing $file"
          #   envsubst < $file > git_manifests/${APP_IMAGE_TAG}/$(basename $file)
          # done
          cd git_manifests
          git config --global user.email "noreply@cycloid.io"
          git config --global user.name "Cycloid Platform"
          git add .
          git diff-index --quiet HEAD || git commit -m "Add ${APP_IMAGE_TAG} manifests"
          
          echo "Generating GitHub comment..."
          GH_PR_URL=https://api.github.com/repos/cycloid-demo/${ORG}-${PROJECT}-app/issues/$(echo ${APP_IMAGE_TAG} | sed 's/pr//g')/comments
          APP_URL="https://($ .component $).${ORG}-${ENV}.${DNS_ZONE}"
          message="✅ Environment deployed at $APP_URL"
          echo $message
          echo "{\"body\": \"$message\"}" | \
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            $GH_PR_URL \
            -d @-
      params:
        ORG: ($ .org $)
        PROJECT: ($ .project $)
        ENV: ($ .env $)
        GITHUB_TOKEN: ((github-pat.token))
        APP_IMAGE_TAG: ((app_image_tag))
        DNS_ZONE: ((dns_zone))
  - put: git_manifests
    params:
      repository: git_manifests


- name: delete-app
  serial: true
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
  - get: git_manifests
  - task: delete-app
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: olivier2t/toolkit
          tag: latest
      inputs:
      - name: git_manifests
      outputs:
      - name: git_manifests
      run:
        path: /bin/bash
        args:
        - -ec
        - |
          echo "Deleting..."
          rm -rf git_manifests/${APP_IMAGE_TAG}
          git config --global user.email "noreply@cycloid.io"
          git config --global user.name "Cycloid Platform"
          git add .
          git diff-index --quiet HEAD || git commit -m "Delete ($ .project $)-($ .env $)-($ .component $) manifests"
  - put: git_manifests
    params:
      repository: git_manifests
