resource_types:
- name: terraform
  type: registry-image
  source:
    repository: cycloid/terraform-resource
    tag: ((terraform_version))


resources:
- name: tfstate
  type: terraform
  icon: terraform
  source:
    env_name: ($ .env $)
    backend_type: http
    backend_config:
      address: '($ .api_url $)/inventory?jwt=($ .inventory_jwt $)'
    vars:
      aws_cred: ((aws_cred))
      github_pat: ((github_pat))
      aws_cred_infra: ((aws_cred_infra))
      azure_cred_infra: ((azure_cred_infra))
      # team_members_infrastructure: ((team_members_infrastructure))
      # team_members_application: ((team_members_application))
      # team_members_integration: ((team_members_integration))
      project_owner: ($ .project_owner $)
      cy_child_org_canonical: ((cy_child_org_canonical))
      aws_region: ((aws_region))
      cy_api_key: ((cy_api_key))
      cy_api_url: ($ .api_url $)
      cy_org: ($ .org $)
      cy_project: ($ .project $)
      cy_env: ($ .env $)
      cy_component: ($ .component $)


# The Terraform stack (will be merged with the config)
- name: git_stack-terraform
  type: git
  icon: github-circle
  source:
    uri: ($ .scs_url $)
    branch: ($ .scs_branch $)
    ($- if eq .scs_cred_type "basic_auth" $)
    username: ((($ .scs_cred_path $).username))
    password: ((($ .scs_cred_path $).password))
    ($- end $)
    ($- if eq .scs_cred_type "ssh" $)
    private_key: ((($ .scs_cred_path $).ssh_key))
    ($- end $)
    paths:
      - ($ .stack_path $)/terraform/*

# The Terraform config (will be merged with the stack)
- name: git_config-terraform
  type: git
  icon: github-circle
  source:
    uri: ($ .cr_url $)
    branch: ($ .cr_branch $)
    ($- if eq .cr_cred_type "basic_auth" $)
    username: ((($ .cr_cred_path $).username))
    password: ((($ .cr_cred_path $).password))
    ($- end $)
    ($- if eq .cr_cred_type "ssh" $)
    private_key: ((($ .cr_cred_path $).ssh_key))
    ($- end $)
    paths:
      - ($ .config_root $)/terraform/*


groups:
- name: overview
  jobs:
    - deploy

- name: destroy
  jobs:
    - destroy


jobs:
  - name: deploy
    serial: true
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - in_parallel:
        - get: git_stack-terraform
          trigger: true
        - get: git_config-terraform
          trigger: true

      - task: create-organization
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          run:
            path: /bin/bash
            args:
            - -c
            - |
              set +e
              cy organization create --name ${CHILD_ORG} --parent-canonical ${ORG} >output 2>&1
              if [[ "$?" != "0" ]]; then
                  echo "Unable to create organization ${CHILD_ORG}"
                  echo "Error: $? - $(cat output)"
              fi

              # Generate an RSA SSH key (2048 bits) and create a Cycloid git ssh credential
              ssh-keygen -t rsa -b 2048 -f /tmp/generated_id_rsa -N ""
              MAX_RETRIES=3
              COUNT=0
              while [ $COUNT -lt $MAX_RETRIES ]; do
                set +e
                cy credential create ssh --name "${CHILD_ORG}-cycloid-git-ssh" --description "SSH key to access Cycloid Git repository" --ssh-key /tmp/generated_id_rsa --org "${CHILD_ORG}"
                if [ $? -eq 0 ]; then
                  echo "Git SSH credential created successfully."
                  break
                fi
                COUNT=$((COUNT + 1))
                echo "Attempt $COUNT failed... retrying"
                sleep 1
              done

          params:
            CHILD_ORG: ((cy_child_org_canonical))
            ORG: ($ .organization $)
            CY_API_URL: ($ .api_url $)
            CY_API_KEY: ((cy_api_key))

      - task: merge-stack-and-config
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          run:
            path: /usr/bin/merge-stack-and-config
          inputs:
          - name: git_config-terraform
            path: "config"
          - name: git_stack-terraform
            path: "stack"
          outputs:
          - name: merged-stack
            path: "merged-stack"
        params:
          CONFIG_PATH: ($ .config_root $)/terraform
          STACK_PATH: ($ .stack_path $)/terraform

      - put: tfstate
        params:
          terraform_source: merged-stack/


      - task: post-config
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          run:
            path: /bin/bash
            args:
            - -c
            - |
              set +e
              # Create admin API key
              MAX_RETRIES=3
              COUNT=0
              while [ $COUNT -lt $MAX_RETRIES ]; do
                set +e
                API_KEY=$(cy api-key create --name "Admin API Key" --rules '[ { "action": "organization:**", "effect": "allow", "resources": [] } ]' --org "${CHILD_ORG}" -o json | jq -r .token)
                if [ $? -eq 0 ]; then
                  echo "API key created successfully."
                  break
                fi
                COUNT=$((COUNT + 1))
                echo "Attempt $COUNT failed... retrying"
                sleep 1
              done

              # Create admin API key credential
              MAX_RETRIES=3
              COUNT=0
              while [ $COUNT -lt $MAX_RETRIES ]; do
                set +e
                cy credential create custom --name "Admin API Key" --canonical "admin-api-key" --description "Cycloid Admin API Key" --field key="$API_KEY" --org "${CHILD_ORG}"
                if [ $? -eq 0 ]; then
                  echo "API key created successfully."
                  break
                fi
                COUNT=$((COUNT + 1))
                echo "Attempt $COUNT failed... retrying"
                sleep 1
              done

              # Create config repository
              MAX_RETRIES=3
              COUNT=0
              while [ $COUNT -lt $MAX_RETRIES ]; do
                set +e
                cy config-repository create --branch config --cred ${CHILD_ORG}-cycloid-git-ssh --name my-config --url "git@github.com:cycloid-demo/${CHILD_ORG}-cycloid.git" --default --org "${CHILD_ORG}"
                if [ $? -eq 0 ]; then
                  echo "Config Repository created successfully."
                  break
                fi
                COUNT=$((COUNT + 1))
                echo "Attempt $COUNT failed... retrying"
                sleep 1
              done

              # Create stacks repositories
              MAX_RETRIES=3
              COUNT=0
              while [ $COUNT -lt $MAX_RETRIES ]; do
                set +e
                cy catalog-repository create --branch stacks --cred ${CHILD_ORG}-cycloid-git-ssh --name my-stacks --url "git@github.com:cycloid-demo/${CHILD_ORG}-cycloid.git" --org "${CHILD_ORG}"
                if [ $? -eq 0 ]; then
                  echo "Catalog Repository created successfully."
                  break
                fi
                COUNT=$((COUNT + 1))
                echo "Attempt $COUNT failed... retrying"
                sleep 1
              done
              MAX_RETRIES=3
              COUNT=0
              while [ $COUNT -lt $MAX_RETRIES ]; do
                set +e
                cy catalog-repository create --branch master --name idp-stacks --url "https://github.com/cycloid-community-catalog/onboarding-stacks-idp.git" --org "${CHILD_ORG}"
                if [ $? -eq 0 ]; then
                  echo "IDP Catalog Repository created successfully."
                  break
                fi
                COUNT=$((COUNT + 1))
                echo "Attempt $COUNT failed... retrying"
                sleep 1
              done

              # Create Infrastructure project and environments
              PROJECT=Infrastructure
              MAX_RETRIES=3
              COUNT=0
              while [ $COUNT -lt $MAX_RETRIES ]; do
                set +e
                cy project create --project "${PROJECT,,}" --name "${PROJECT}" --org "${CHILD_ORG}" --update
                if [ $? -eq 0 ]; then
                  echo "Project ${PROJECT} created successfully."
                  break
                fi
                COUNT=$((COUNT + 1))
                echo "Attempt $COUNT failed... retrying"
                sleep 1
              done

              for enviter in "OTH" "PPE" "PRD"
              do
                MAX_RETRIES=3
                COUNT=0
                while [ $COUNT -lt $MAX_RETRIES ]; do
                  set +e
                  cy environment create --project "${PROJECT,,}" --env "${enviter,,}" --name "${enviter}" --org "${CHILD_ORG}" --update
                  if [ $? -eq 0 ]; then
                    echo "Environment ${enviter} created successfully."
                    break
                  fi
                  COUNT=$((COUNT + 1))
                  echo "Attempt $COUNT failed... retrying"
                  sleep 1
                done
              done

              # Create Application project and environments
              PROJECT=Application
              MAX_RETRIES=3
              COUNT=0
              while [ $COUNT -lt $MAX_RETRIES ]; do
                set +e
                cy project create --project "${PROJECT,,}" --name "${PROJECT}" --org "${CHILD_ORG}" --update
                if [ $? -eq 0 ]; then
                  echo "Project ${PROJECT} created successfully."
                  break
                fi
                COUNT=$((COUNT + 1))
                echo "Attempt $COUNT failed... retrying"
                sleep 1
              done

              for enviter in "OTH-DEV" "OTH-TST" "PPE" "PRD"
              do
                MAX_RETRIES=3
                COUNT=0
                while [ $COUNT -lt $MAX_RETRIES ]; do
                  set +e
                  cy environment create --project "${PROJECT,,}" --env "${enviter,,}" --name "${enviter}" --org "${CHILD_ORG}" --update
                  if [ $? -eq 0 ]; then
                    echo "Environment ${enviter} created successfully."
                    break
                  fi
                  COUNT=$((COUNT + 1))
                  echo "Attempt $COUNT failed... retrying"
                  sleep 1
                done
              done


              curl -X POST "${CY_API_URL}/organizations/${CHILD_ORG}/roles"\
                -H "Content-type: application/vnd.cycloid.io.v1+json" \
                -H "authorization: Bearer ${CY_API_KEY}" \
                --data-raw '{ "name": "Infrastructure", "canonical": "infrastructure", "description": "Role to access the infrastructure stacks and projects", "rules": [ { "action": "organization:read", "effect": "allow", "resources": [] }, { "action": "organization:child:read", "effect": "allow", "resources": [] }, { "action": "organization:cloud_provider:read", "effect": "allow", "resources": [] }, { "action": "organization:config_repository:list", "effect": "allow", "resources": [] }, { "action": "organization:config_repository:read", "effect": "allow", "resources": [] }, { "action": "organization:credential:list", "effect": "allow", "resources": [] }, { "action": "organization:environment:read", "effect": "allow", "resources": [] }, { "action": "organization:event:list", "effect": "allow", "resources": [] }, { "action": "organization:external_backend:read", "effect": "allow", "resources": [] }, { "action": "organization:inventory_resource:list", "effect": "allow", "resources": [] }, { "action": "organization:kpi:read", "effect": "allow", "resources": [] }, { "action": "organization:member:read", "effect": "allow", "resources": [] }, { "action": "organization:pipeline:read", "effect": "allow", "resources": [] }, { "action": "organization:project:read", "effect": "allow", "resources": [ "organization:'${CHILD_ORG}':project:infrastructure" ] }, { "action": "organization:project:update", "effect": "allow", "resources": [] }, { "action": "organization:service_catalog:read", "effect": "allow", "resources": [ "organization:'${CHILD_ORG}':service_catalog:'${CHILD_ORG}':stack-kind-argocd", "organization:'${CHILD_ORG}':service_catalog:'${CHILD_ORG}':stack-postgresql-idp" ] }, { "action": "organization:service_catalog:list", "effect": "allow", "resources": [ "organization:'${CHILD_ORG}':service_catalog:'${CHILD_ORG}':stack-kind-argocd", "organization:'${CHILD_ORG}':service_catalog:'${CHILD_ORG}':stack-postgresql-idp" ] } ] }' | jq .

              curl -X POST "${CY_API_URL}/organizations/${CHILD_ORG}/roles"\
                -H "Content-type: application/vnd.cycloid.io.v1+json" \
                -H "authorization: Bearer ${CY_API_KEY}" \
                --data-raw '{ "name": "Application", "canonical": "application", "description": "Role to access the application stacks and projects", "rules": [ { "action": "organization:read", "effect": "allow", "resources": [] }, { "action": "organization:child:read", "effect": "allow", "resources": [] }, { "action": "organization:cloud_provider:read", "effect": "allow", "resources": [] }, { "action": "organization:config_repository:list", "effect": "allow", "resources": [] }, { "action": "organization:config_repository:read", "effect": "allow", "resources": [] }, { "action": "organization:credential:list", "effect": "allow", "resources": [] }, { "action": "organization:environment:read", "effect": "allow", "resources": [] }, { "action": "organization:event:list", "effect": "allow", "resources": [] }, { "action": "organization:external_backend:read", "effect": "allow", "resources": [] }, { "action": "organization:inventory_resource:list", "effect": "allow", "resources": [] }, { "action": "organization:kpi:read", "effect": "allow", "resources": [] }, { "action": "organization:member:read", "effect": "allow", "resources": [] }, { "action": "organization:pipeline:read", "effect": "allow", "resources": [] }, { "action": "organization:project:read", "effect": "allow", "resources": [ "organization:'${CHILD_ORG}':project:application" ] }, { "action": "organization:project:update", "effect": "allow", "resources": [] }, { "action": "organization:service_catalog:read", "effect": "allow", "resources": [ "organization:'${CHILD_ORG}':service_catalog:'${CHILD_ORG}':stack-project-github-gitops-idp", "organization:'${CHILD_ORG}':service_catalog:'${CHILD_ORG}':stack-postgresql-idp" ] }, { "action": "organization:service_catalog:list", "effect": "allow", "resources": [ "organization:'${CHILD_ORG}':service_catalog:'${CHILD_ORG}':stack-kind-argocd", "organization:'${CHILD_ORG}':service_catalog:'${CHILD_ORG}':stack-postgresql-idp" ] } ] }' | jq .

              curl -X POST "${CY_API_URL}/organizations/${CHILD_ORG}/teams" \
                -H "Content-type: application/vnd.cycloid.io.v1+json" \
                -H "authorization: Bearer ${CY_API_KEY}" \
                --data-raw '{ "name": "Infrastructure", "canonical": "infrastructure", "owner": "($ .project_owner $)", "roles_canonical": [ "read-all", "infrastructure" ] }' | jq .

              curl -X POST "${CY_API_URL}/organizations/${CHILD_ORG}/teams" \
                -H "Content-type: application/vnd.cycloid.io.v1+json" \
                -H "authorization: Bearer ${CY_API_KEY}" \
                --data-raw '{ "name": "Application", "canonical": "application", "owner": "($ .project_owner $)", "roles_canonical": [ "read-all", "application" ] }' | jq .
              
              # Invite team members to the Infrastructure team
              echo "${TEAM_MEMBERS_INFRASTRUCTURE}" | jq -r '.[]' | while read -r member
              do
                echo "Inviting ${member} to the Infrastructure team"
                curl -X POST "${CY_API_URL}/organizations/${CHILD_ORG}/members" \
                  -H "Content-type: application/vnd.cycloid.io.v1+json" \
                  -H "authorization: Bearer ${CY_API_KEY}" \
                  --data-raw '{ "email": "'${member}'", "role_canonical": "infrastructure" }' | jq .
                curl -X POST "${CY_API_URL}/organizations/${CHILD_ORG}/teams/infrastructure/members" \
                  -H "Content-type: application/vnd.cycloid.io.v1+json" \
                  -H "authorization: Bearer ${CY_API_KEY}" \
                  --data-raw '{ "username": "'${member}'" }' | jq .
              done

              # Invite team members to the Application team
              echo "${TEAM_MEMBERS_APPLICATION}" | jq -r '.[]' | while read -r member
              do
                echo "Inviting ${member} to the Application team"
                curl -X POST "${CY_API_URL}/organizations/${CHILD_ORG}/members" \
                  -H "Content-type: application/vnd.cycloid.io.v1+json" \
                  -H "authorization: Bearer ${CY_API_KEY}" \
                  --data-raw '{ "email": "'${member}'", "role_canonical": "application" }' | jq .
                curl -X POST "${CY_API_URL}/organizations/${CHILD_ORG}/teams/application/members" \
                  -H "Content-type: application/vnd.cycloid.io.v1+json" \
                  -H "authorization: Bearer ${CY_API_KEY}" \
                  --data-raw '{ "username": "'${member}'" }' | jq .
              done
          params:
            CHILD_ORG: ((cy_child_org_canonical))
            TEAM_MEMBERS_INFRASTRUCTURE: ((team_members_infrastructure))
            TEAM_MEMBERS_APPLICATION: ((team_members_application))
            TEAM_MEMBERS_INTEGRATION: ((team_members_integration))
            ORG: ($ .organization $)
            CY_API_URL: ($ .api_url $)
            CY_API_KEY: ((cy_api_key))


  - name: destroy
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - in_parallel:
        - get: git_stack-terraform
          trigger: false
        - get: git_config-terraform
          trigger: false
        - get: tfstate
          trigger: false

      - task: merge-stack-and-config
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          run:
            path: /usr/bin/merge-stack-and-config
          inputs:
          - name: git_config-terraform
            path: "config"
          - name: git_stack-terraform
            path: "stack"
          outputs:
          - name: merged-stack
            path: "merged-stack"
        params:
          CONFIG_PATH: ($ .config_root $)/terraform
          STACK_PATH: ($ .stack_path $)/terraform

      - put: tfstate
        params:
          action: destroy
          terraform_source: merged-stack/
        get_params:
          action: destroy