resource_types:
- name: terraform
  type: registry-image
  source:
    repository: cycloid/terraform-resource
    tag: ((terraform_version))


resources:
- name: tfstate
  type: terraform
  icon: terraform
  source:
    env_name: ($ .env $)
    backend_type: http
    backend_config:
      address: '($ .api_url $)/inventory?jwt=($ .inventory_jwt $)'
    vars:
($- if eq .use_case "organization" $)
      aws_cred: ((aws_cred))
      github_pat: ((github_pat))
($- else if eq .use_case "members" $)
      team_members_ccp_csp: ((team_members_ccp_csp))
      team_members_sods: ((team_members_sods))
      team_members_csds: ((team_members_csds))
($- end $)
      cy_child_org_canonical: ((cy_child_org_canonical))
      aws_region: ((aws_region))
      cy_api_key: ((cy_api_key))
      cy_api_url: ($ .api_url $)
      cy_org: ($ .org $)
      cy_project: ($ .project $)
      cy_env: ($ .env $)
      cy_component: ($ .component $)


# The Terraform stack (will be merged with the config)
- name: git_stack-terraform
  type: git
  icon: github-circle
  source:
    uri: ($ .scs_url $)
    branch: ($ .scs_branch $)
    ($- if eq .scs_cred_type "basic_auth" $)
    username: ((($ .scs_cred_path $).username))
    password: ((($ .scs_cred_path $).password))
    ($- end $)
    ($- if eq .scs_cred_type "ssh" $)
    private_key: ((($ .scs_cred_path $).ssh_key))
    ($- end $)
    paths:
      - ($ .stack_path $)/terraform/($ .use_case $)/*

# The Terraform config (will be merged with the stack)
- name: git_config-terraform
  type: git
  icon: github-circle
  source:
    uri: ($ .cr_url $)
    branch: ($ .cr_branch $)
    ($- if eq .cr_cred_type "basic_auth" $)
    username: ((($ .cr_cred_path $).username))
    password: ((($ .cr_cred_path $).password))
    ($- end $)
    ($- if eq .cr_cred_type "ssh" $)
    private_key: ((($ .cr_cred_path $).ssh_key))
    ($- end $)
    paths:
      - ($ .config_root $)/terraform/($ .use_case $)/*


groups:
- name: overview
  jobs:
    - deploy

- name: destroy
  jobs:
    - destroy


jobs:
  - name: deploy
    serial: true
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - in_parallel:
        - get: git_stack-terraform
          trigger: true
        - get: git_config-terraform
          trigger: true

($- if eq .use_case "organization" $)
      - task: create-organization
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          run:
            path: /bin/bash
            args:
            - -c
            - |
              set +e
              cy organization create --name ${CHILD_ORG} --parent-canonical ${ORG} >output 2>&1
              if [[ "$?" != "0" ]]; then
                  echo "Unable to create organization ${CHILD_ORG}"
                  echo "Error: $? - $(cat output)"
              fi

              for projiter in "Infrastructure" "Application"
              do
                MAX_RETRIES=30
                COUNT=0
                while [ $COUNT -lt $MAX_RETRIES ]; do
                  set +e
                  cy project create --project "${projiter,,}" --name "${projiter}" --org "${CHILD_ORG}" --update
                  if [ $? -eq 0 ]; then
                    echo "Project ${projiter} created successfully."
                    break
                  fi
                  COUNT=$((COUNT + 1))
                  echo "Attempt $COUNT failed... retrying"
                  sleep 1
                done

                for enviter in "OTH-DEV" "PPE" "PRD"
                do
                  MAX_RETRIES=30
                  COUNT=0
                  while [ $COUNT -lt $MAX_RETRIES ]; do
                    set +e
                    cy environment create --project "${projiter,,}" --env "${enviter,,}" --name "${enviter}" --org "${CHILD_ORG}" --update
                    if [ $? -eq 0 ]; then
                      echo "Environment ${enviter} created successfully."
                      break
                    fi
                    COUNT=$((COUNT + 1))
                    echo "Attempt $COUNT failed... retrying"
                    sleep 1
                  done
                done
              done
          params:
            CHILD_ORG: ((cy_child_org_canonical))
            ORG: ($ .organization $)
            CY_API_URL: ($ .api_url $)
            CY_API_KEY: ((cy_api_key))
($- end $)

      - task: merge-stack-and-config
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          run:
            path: /usr/bin/merge-stack-and-config
          inputs:
          - name: git_config-terraform
            path: "config"
          - name: git_stack-terraform
            path: "stack"
          outputs:
          - name: merged-stack
            path: "merged-stack"
        params:
          CONFIG_PATH: ($ .config_root $)/terraform/($ .use_case $)
          STACK_PATH: ($ .stack_path $)/terraform/($ .use_case $)

      - put: tfstate
        params:
          terraform_source: merged-stack/


  - name: destroy
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - in_parallel:
        - get: git_stack-terraform
          trigger: false
        - get: git_config-terraform
          trigger: false
        - get: tfstate
          trigger: false

      - task: merge-stack-and-config
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: cycloid/cycloid-toolkit
              tag: latest
          run:
            path: /usr/bin/merge-stack-and-config
          inputs:
          - name: git_config-terraform
            path: "config"
          - name: git_stack-terraform
            path: "stack"
          outputs:
          - name: merged-stack
            path: "merged-stack"
        params:
          CONFIG_PATH: ($ .config_root $)/terraform/($ .use_case $)
          STACK_PATH: ($ .stack_path $)/terraform/($ .use_case $)

      - put: tfstate
        params:
          action: destroy
          terraform_source: merged-stack/
        get_params:
          action: destroy