---
version: "2"
use_cases:
- name: default
  sections:
  - name: ArgoCD
    groups:
    - name: ArgoCD
      technologies: [terraform]
      vars:
      - name: "ArgoCD Version"
        description: "Version of ArgoCD to deploy"
        key: argocd_version
        widget: simple_text
        type: string
        default: "7.8.3"
        required: true
        validations: 
        - regexp: "^\\d+\\.\\d+\\.\\d+$" 
          error_message: "Please enter a valid ArgoCD version such as 7.8.3"

    - name: GitHub
      technologies: [pipeline]
      vars:
      - name: "GitHub PAT"
        description: "GitHub Personal Access Token allowing to create the new ArgoCD repository"
        key: github_pat
        widget: cy_cred
        widget_config:
          cred_types: ["custom"]
        type: string
        default: "((github-pat.key))"
        required: true